<div id="principal">
              <p>o ser perguntada sobre as críticas dos empresários em relação a alta   carga tributária no país, a presidente disse ter "plena consciência de   que o país precisa reduzir a carga tributária". "Eu também reclamo muito   do sistema tributário. Mas eu não posso supor que minha opinião pessoal   seja minha opinião como presidente da República. [...] Dentro do meu   período governamental, farei o possível para reduzir a carga   tributária", afirmou.</p>
              <p> A presidente citou ainda "interesses envolvidos" na questão da reforma   tributária, como o impacto na arrecadação de municípios, estados e   União, e afirmou que tem tomado "medidas pontuais" para ajudar o setor   privado.</p>
              <p> O processo de desoneração da folha de pagamentos teve início no ano   passado com o lançamento do plano "Brasil Maior", de estímulos para a   indústria. Em troca dos 20% de contribuição patronal do Instituto   Nacional do Seguro Social (INSS), os setores que estão no processo de   desoneração da folha de pagamentos (confecção, calçados e "call   centers") têm seu faturamento tributado em 1,5%. O setor de "softwares",   por sua vez, paga 2,5% sobre o faturamento em troca da desoneração da   folha.</p>
              <p>o ser perguntada sobre as críticas dos empresários em relação a alta   carga tributária no país, a presidente disse ter "plena consciência de   que o país precisa reduzir a carga tributária". "Eu também reclamo muito   do sistema tributário. Mas eu não posso supor que minha opinião pessoal   seja minha opinião como presidente da República. [...] Dentro do meu   período governamental, farei o possível para reduzir a carga   tributária", afirmou.</p>
              <p> A presidente citou ainda "interesses envolvidos" na questão da reforma   tributária, como o impacto na arrecadação de municípios, estados e   União, e afirmou que tem tomado "medidas pontuais" para ajudar o setor   privado.</p>
              <p> O processo de desoneração da folha de pagamentos teve início no ano   passado com o lançamento do plano "Brasil Maior", de estímulos para a   indústria. Em troca dos 20% de contribuição patronal do Instituto   Nacional do Seguro Social (INSS), os setores que estão no processo de   desoneração da folha de pagamentos (confecção, calçados e "call   centers") têm seu faturamento tributado em 1,5%. O setor de "softwares",   por sua vez, paga 2,5% sobre o faturamento em troca da desoneração da   folha.</p>
            </div>
			<!-- espaço -->
             <div class="spacer"></div>